$(document).ready(function () {
    $("#more").parent().on("click", "#more", function () {
        $("#more").text("Less");
        $("#more").attr("id", "less");
    });
    $("#more").parent().on("click", "#less", function () {
        $("#less").text("More");
        $("#less").attr("id", "more");
    });

    $("#more1").parent().on("click", "#more1", function () {
        $("#more1").text("Less");
        $("#more1").attr("id", "less1");
    });
    $("#more1").parent().on("click", "#less1", function () {
        $("#less1").text("More");
        $("#less1").attr("id", "more1");
    });

    // Script to open and close sidebar
    function w3_open() {
        document.getElementById('mySidebar').style.display = 'block';
        document.getElementById('myOverlay').style.display = 'block';
    }

    function w3_close() {
        document.getElementById('mySidebar').style.display = 'none';
        document.getElementById('myOverlay').style.display = 'none';
    }
    $("#«").click(function () {
        $("#portfolios").html("<div class='w3-third w3-container w3-margin-bottom'><img src='img/sc.jpg' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>The impact of technology on music</h5></b></p><p><b>Discipline:</b> Computational Systems</p><p><b>Description:</b> Idea of ​​computational innovation in the field of music based on past and present artifacts and plans already thought about the future in order to create something innovative</p><p><a href='pdf/sc.pdf' target='_blank'> <i class='fa fa-file w3-hover-opacity'><b> PDF</b></i></a></p><p><b>Final grade:</b> 16/20</p></div></div><div class='w3-third w3-container w3-margin-bottom'><img src='img/taw.jpg' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>Promotional video</h5></b></p><p><b>Discipline:</b> Web Technologies and Applications</p><p><b>Description:</b> Realization for the field of Technologies and Web Applications, a video that helps in the dissemination of the course on Technologies and Information Systems for the Web, since it is a relatively recent course about which there is not much information yet</p><p><a href='https://youtu.be/voYTuVmvGUk' target='_blank'> <i class='fa fa-play-circle w3-hover-opacity'><b> video</b></i></a><a href='pdf/taw.pdf' target='_blank'> <i class='fa fa-file w3-hover-opacity'><b> PDF</b></i></a></p><p><b>Final grade:</b> 16/20</p></div></div><div class='w3-third w3-container'><img src='img/P1.png' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>Lost and Found Software</h5></b></p><p><b>Discipline:</b> Project I</p><p><b>Description:</b> Realization for the field of Technologies and Web Applications, a video that helps in the dissemination of the course on Technologies and Information Systems for the Web, since it is a relatively recent course about which there is not much information yet</p><p><a href='https://github.com/andregouveia8/softlost' target='_blank'> <i class='fa fa-code w3-hover-opacity'><b> code</b></i></a><a href='https://youtu.be/VLuBi00ivvQ' target='_blank'> <i class='fa fa-play-circle w3-hover-opacity'><b> video</b></i></a><a href='pdf/p1.pdf' target='_blank'> <i class='fa fa-file w3-hover-opacity'><b> PDF</b></i></a></p><p><b>Final grade:</b> 15/20</p></div></div>")
    });

    $("#one").click(function () {
        $("#portfolios").html("<div class='w3-third w3-container w3-margin-bottom'><img src='img/sc.jpg' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>The impact of technology on music</h5></b></p><p><b>Discipline:</b> Computational Systems</p><p><b>Description:</b> Idea of ​​computational innovation in the field of music based on past and present artifacts and plans already thought about the future in order to create something innovative</p><p><a href='pdf/sc.pdf' target='_blank'> <i class='fa fa-file w3-hover-opacity'><b> PDF</b></i></a></p><p><b>Final grade:</b> 16/20</p></div></div><div class='w3-third w3-container w3-margin-bottom'><img src='img/taw.jpg' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>Promotional video</h5></b></p><p><b>Discipline:</b> Web Technologies and Applications</p><p><b>Description:</b> Realization for the field of Technologies and Web Applications, a video that helps in the dissemination of the course on Technologies and Information Systems for the Web, since it is a relatively recent course about which there is not much information yet</p><p><a href='https://youtu.be/voYTuVmvGUk' target='_blank'> <i class='fa fa-play-circle w3-hover-opacity'><b> video</b></i></a><a href='pdf/taw.pdf' target='_blank'> <i class='fa fa-file w3-hover-opacity'><b> PDF</b></i></a></p><p><b>Final grade:</b> 16/20</p></div></div><div class='w3-third w3-container'><img src='img/P1.png' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>Lost and Found Software</h5></b></p><p><b>Discipline:</b> Project I</p><p><b>Description:</b> Realization for the field of Technologies and Web Applications, a video that helps in the dissemination of the course on Technologies and Information Systems for the Web, since it is a relatively recent course about which there is not much information yet</p><p><a href='https://github.com/andregouveia8/softlost' target='_blank'> <i class='fa fa-code w3-hover-opacity'><b> code</b></i></a><a href='https://youtu.be/VLuBi00ivvQ' target='_blank'> <i class='fa fa-play-circle w3-hover-opacity'><b> video</b></i></a><a href='pdf/p1.pdf' target='_blank'> <i class='fa fa-file w3-hover-opacity'><b> PDF</b></i></a></p><p><b>Final grade:</b> 15/20</p></div></div>")
    });

    $("#two").click(function () {
        $("#portfolios").html("<div class='w3-third w3-container w3-margin-bottom'><img src='img/design.jpg' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>Social network APP</h5></b></p><p><b>Discipline:</b> Design</p><p><b>Description:</b> Development of a social network through mockups</p><p><a href='pdf/design.pdf' target='_blank'> <i class='fa fa-file w3-hover-opacity'><b> PDF</b></i></a></p><p><b>Final grade:</b> ---</p></div></div><div class='w3-third w3-container w3-margin-bottom'><img src='img/agpuzzle.jpg' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>English Puzzle</h5></b></p><p><b>Discipline:</b> Graphic Animation</p><p><b>Description:</b> The website in question corresponds to a game that allows the user to understand a little more of the English language by relating the images of the animals to their respective names, which is educational for the youngest.</p><p><a href='https://cdn.rawgit.com/acacmt/Puzzle-Ingl-s/9cab2a1b/Menu.html' target='_blank'> <i class='fa fa-link w3-hover-opacity'><b> link</b></i></a><a href='https://github.com/acacmt/Puzzle-Ingl-s' target='_blank'> <i class='fa fa-code w3-hover-opacity'><b> code</b></i></a><a href='pdf/puzzle.pdf' target='_blank'> <i class='fa fa-file w3-hover-opacity'><b> PDF</b></i></a></p><p><b>Final grade:</b> 17/20</p></div></div><div class='w3-third w3-container'><img src='img/aganim.jpg' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>Intro ESMAD</h5></b></p><p><b>Discipline:</b> Graphic Animation</p><p><b>Description:</b> The website in question was made based on visual elements in order to impress and captivate users of the platform in order to impact them.</p><p><a href='https://cdn.rawgit.com/acacmt/Intro-Esmad/03593343/ESMAD.html' target='_blank'> <i class='fa fa-link w3-hover-opacity'><b> link</b></i></a><a href='https://github.com/acacmt/Intro-Esmad' target='_blank'> <i class='fa fa-code w3-hover-opacity'><b> code</b></i></a><a href='pdf/intro.pdf' target='_blank'> <i class='fa fa-file w3-hover-opacity'><b> PDF</b></i></a></p><p><b>Final grade:</b> 17/20</p></div></div>")
    });
    $("#three").click(function () {
        $("#portfolios").html("<div class='w3-third w3-container w3-margin-bottom'><img src='img/ams.jpg' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>NETSIW Core</h5></b></p><p><b>Discipline:</b> System Analysis and Modeling</p><p><b>Description:</b> The group, consisting of three elements, had to develop the design of an information system to support the management of the Nucleus of Former Students of the Degree in TSIW (NexTSIW) in order to maintain alumni contact with the course and the school.</p><p><a href='pdf/ams.pdf' target='_blank'><i class='fa fa-file w3-hover-opacity'><b> PDF</b></i></a></p><p><b>Final grade:</b> 15/20</p></div></div><div class='w3-third w3-container w3-margin-bottom'><img src='img/BD.png' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>Conference 'Comic Con'</h5></b></p><p><b>Discipline:</b> Database</p><p><b>Description:</b> The group of three elements had to develop the design and implementation of a database to support the management of a company's events in order to correct possible gaps</p><p><a href='pdf/bd.pdf' target='_blank'> <i class='fa fa-file w3-hover-opacity'><b> PDF</b></i></a></p><p><b>Final grade:</b> 17/20</p></div></div><div class='w3-third w3-container'><img src='img/Pw1.jpg' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>BiConde</h5></b></p><p><b>Discipline:</b> Web Programming I</p><p><b>Description:</b> The website in question was made based on visual elements in order to impress and captivate users of the platform in order to impact them and use the same.</p><p><a href='https://cdn.rawgit.com/acacmt/biConde/1e92b7d7/Menu.html' target='_blank'> <i class='fa fa-link w3-hover-opacity'><b> link</b></i></a><a href='https://github.com/acacmt/biConde' target='_blank'> <i class='fa fa-code w3-hover-opacity'><b> code</b></i></a></p><p><b>Final grade:</b> 15/20</p></div></div>")
    });
    $("#four").click(function () {
        $("#portfolios").html("<div class='w3-third w3-container w3-margin-bottom'><img src='img/sgtank.jpg' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>Bomber Tank</h5></b></p><p><b>Discipline:</b> Graphic Systems</p><p><b>Description:</b> The group, consisting of three elements, had to develop a website through a mini-game.</p><p><a href='https://cdn.rawgit.com/acacmt/BomberTank/acd801d5/Jogo%20Tank/Tank.html' target='_blank'> <i class='fa fa-link w3-hover-opacity'><b> link</b></i></a><a href='https://github.com/acacmt/BomberTank' target='_blank'> <i class='fa fa-code w3-hover-opacity'><b> code</b></i></a></p><p><b>Final grade:</b> 16/20</p></div></div><div class='w3-third w3-container w3-margin-bottom'><img src='img/sgtic.jpg' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>Tic Tac Toe</h5></b></p><p><b>Discipline:</b> Graphic Systems</p><p><b>Description:</b> The website in question consisted of the development of a mini-game.</p><p><a href='https://cdn.rawgit.com/acacmt/Tic-Tac-Toe/fb4087f1/TicTacToeMenu.html' target='_blank'> <i class='fa fa-link w3-hover-opacity'><b> link</b></i></a><a href='https://github.com/acacmt/Tic-Tac-Toe' target='_blank'> <i class='fa fa-code w3-hover-opacity'><b> code</b></i></a><a href='pdf/tictac.pdf' target='_blank'> <i class='fa fa-file w3-hover-opacity'><b> PDF</b></i></a><p><b>Final grade:</b> ---</p></div></div><div class='w3-third w3-container'><img src='img/P2.png' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>LogSpot</h5></b></p><p><b>Discipline:</b> Project II</p><p><b>Description:</b> The website in question was made based on visual elements in order to impress and captivateusers of the platform in order to impact them.</p><p><a href='http://logspot.herokuapp.com/' target='_blank'> <i class='fa fa-link w3-hover-opacity'><b> link</b></i></a><a href='https://youtu.be/YIDGEE7F-O4' target='_blank'> <i class='fa fa-play-circle w3-hover-opacity'><b> video</b></i></a><a href='pdf/p2.pdf' target='_blank'> <i class='fa fa-file w3-hover-opacity'><b> PDF</b></i></a></p><p><b>Final grade:</b> 18/20</p></div></div>")
    });
    $("#five").click(function () {
        $("#portfolios").html("<div class='w3-third w3-container'><img src='img/ma3d.jpg' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>PolyTroopers</h5></b></p><p><b>Discipline:</b> Modeling and 3D environments</p><p><b>Description:</b> The group of three members, developed the modeling of an animation of according to the chosen theme and made a video where it was inserted using sound elements of the pre-production, ie, inspirations, concept design, storyboard, animatic and a name chosen by members of the group</p><p><a href='https://we.tl/Pv4wDfaEIe' target='_blank'><i class='fa fa-play-circle w3-hover-opacity'><b> video</b></i></a><a href='pdf/ma3d.pdf' target='_blank'> <i class='fa fa-file w3-hover-opacity'><b> PDF</b></i></a></p><p><b>Final grade:</b> 18/20</p></div></div>")
    });
    $("#»").click(function () {
        $("#portfolios").html("<div class='w3-third w3-container'><img src='img/ma3d.jpg' alt='Image not found!' style='width:100%' class='w3-hover-opacity'><div class='w3-container w3-white'><br><p><b><h5>PolyTroopers</h5></b></p><p><b>Discipline:</b> Modeling and 3D environments</p><p><b>Description:</b> The group of three members, developed the modeling of an animation of according to the chosen theme and made a video where it was inserted using sound elements of the pre-production, ie, inspirations, concept design, storyboard, animatic and a name chosen by members of the group</p><p><a href='https://we.tl/Pv4wDfaEIe' target='_blank'><i class='fa fa-play-circle w3-hover-opacity'><b> video</b></i></a><a href='pdf/ma3d.pdf' target='_blank'> <i class='fa fa-file w3-hover-opacity'><b> PDF</b></i></a></p><p><b>Final grade:</b> 18/20</p></div></div>")
    });
});